modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/JackyyTV/NoAutoJump/issues"
displayURL="https://github.com/JackyyTV/NoAutoJump"

[[mods]]
modId="noautojump"
version="1.13.2-1.0"
displayName="No Auto Jump"
authors="Jackyy"
description='''
Simply forces Auto-Jump to be disabled!
'''

[[dependencies.noautojump]]
    modId="forge"
    mandatory=true
    versionRange="[24,)"
    ordering="NONE"
    side="BOTH"
